---
  version: "3"
  services:

    flask:
        build:
          dockerfile: './custom_nginx'
          context: '.'
        environment:
            - FLASK_APP=/usr/src/app/project/app.py
        command: flask run --host=0.0.0.0
        ports:
          - 5000:5000
        dns:
          - 127.0.0.11
        networks:
          - demo_app
    web:
      #image: nginx
      build:
        dockerfile: './custom_nginx'
        context: '.'
      ports:
        - 8080:80
      volumes:
        - web_vol:/usr/share/nginx/html
      networks:
        - demo_app
      command: nginx -g 'daemon off;'
      restart: always
      dns:
        - 127.0.0.11
      depends_on:
        - db
        - flask
    db:
      build:
        dockerfile: './custom_mariadb'
        context: '.'
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ukpostcodes
        MYSQL_USER: postcodes
        MYSQL_PASSWORD: secret
      ports:
        - 3306:3306
      volumes:
        - mysql_vol:/var/lib/mysql
      networks:
        - demo_app
      restart: always
      dns:
        - 127.0.0.11

  networks:
    demo_app:

  volumes:
    web_vol:
    mysql_vol:
